### PR TITLE
fix: improve error messages

### LINKED ISSUE #416: Unhelpful error message on validation error
**Describe the bug**

When trying to run a recipe with an invalid config, the error message is unhelpful

**To Reproduce**

Use a recipe that does not have one of the required fields and attempt to run it:

```yaml
name: shield-integration
version: v1beta1
source:
  name: shield
  scope: shield-integration
  config:
    h0st: p-godata-systems-shield-v2.golabs.io:80
sinks:
  - name: console
```

```
$ meteor run ./_recipes/tmp-shield-integration.yaml
unable to find config file, loading from env and defaults: open ./meteor.yaml: no such file or directory
INFO[0000] running recipe                                recipe=shield-integration
ERRO[0000] error running recipe                          duration_ms=0 err="failed to setup extractor: could not initiate extractor \"shield\": invalid  config" recipe=shield-integration records_count=0
ERRO[0000] failed to setup extractor: could not initiate extractor "shield": invalid  config
running recipes  100% |████████████████████████████████████████| (1/1)
Some recipes were not successful
1 failing, 0 successful, and 1 total

Status	Recipe            	Source	Duration(ms)	Records
✘     	shield-integration	shield	0 ms        	0
```

**Expected behavior**

The error message should communicate the details of the validation failure.

### PR DESCRIPTION
**Pull request by sudo-suhas**
- Include plugin name in the error message when it is not found.
- Include the validation failure message along with the line number in
  the error message for plugin config.
- During lint, include the recipe name while printing errors that are 
  neither 'not found' nor 'invalid config' errors.
- During run, on run failure, include recipe name in the error log 
  context.
- Include details of the validation failures in the error message for
  InvalidConfigError. This gets printed while trying to run the recipe.

BEFORE:

    $ meteor run run ./_recipes/caramlstore-stg-wth-script-invalid.yaml
    INFO[0000] running recipe                                recipe=caramlstore-stg-wth-script-invalid
    ERRO[0000] error running recipe                          duration_ms=189 err="failed to setup processor: could not initiate processor \"script\": script processor init: invalid  config" recipe=caramlstore-stg-wth-script-invalid records_count=0
    ERRO[0000] failed to setup processor: could not initiate processor "script": script processor init: invalid  config
    ...

    $ meteor lint ./_recipes
    caramlstore-stg-wth-script-invalid: invalid script processor config on line: 13
    caramlstore-stg-wth-script-invalid: invalid script processor config: Key: 'Config.script' Error:Field validation for 'script' failed on the 'required' tag
    recipe error: urn scope is required to generate unique urn
    kafka-to-http: invalid labels processor config: Key: 'Config.labels' Error:Field validation for 'labels' failed on the 'required' tag
    service_yaml-test: invalid extractor on line: 4
    shield-integration: invalid shield extractor config: Key: 'Config.host' Error:Field validation for 'host' failed on the 'required' tag
    ...

AFTER:

    $ meteor run run ./_recipes/caramlstore-stg-wth-script-invalid.yaml
    INFO[0000] running recipe                                recipe=caramlstore-stg-wth-script-invalid
    ERRO[0000] error running recipe                          duration_ms=205 err="failed to setup processor: could not initiate processor \"script\": script processor init: invalid config:     * validation for field 'engine' failed on the 'oneof' tag\n\t * validation for field 'script' failed on the 'required' tag" recipe=caramlstore-stg-wth-script-invalid records_count=0
    ERRO[0000] failed to setup processor: could not initiate processor "script": script processor init: invalid config:
         * validation for field 'engine' failed on the 'oneof' tag
         * validation for field 'script' failed on the 'required' tag  recipe=caramlstore-stg-wth-script-invalid
    ...

    $ meteor lint ./_recipes
    caramlstore-stg-wth-script-invalid: invalid script processor config on line: 13: validation for field 'engine' failed on the 'oneof' tag
    caramlstore-stg-wth-script-invalid: invalid script processor config: validation for field 'script' failed on the 'required' tag
    kafka-to-http: recipe error: urn scope is required to generate unique urn
    kafka-to-http: invalid labels processor config: validation for field 'labels' failed on the 'required' tag
    service_yaml-test: invalid 'service_yaml' extractor on line: 4
    shield-integration: invalid shield extractor config: validation for field 'host' failed on the 'required' tag
Closes #416

### CODE REVIEW

File: plugins/base_extractor.go [hunk 1]
```diff
@@ -15,7 +15,9 @@ func NewBaseExtractor(info Info, configRef interface{}) BaseExtractor {
 // Validate checks if the given options is valid for the plugin.
 func (p *BaseExtractor) Validate(config Config) error {
 	if config.URNScope == "" {
-		return ErrEmptyURNScope
+		return InvalidConfigError{Errors: []ConfigError{
```
Comment (StewartJingga) [inline plugins/base_extractor.go:18]: technically `scope` is not part of the config 🤔 .
Should we have different error for this?

Comment (sudo-suhas) [reply plugins/base_extractor.go:18]: Without that, you don't get to know which recipe has the issue:

```
recipe error: urn scope is required to generate a unique urn
```

With this change:
```
kafka-to-http: invalid kafka extractor config: urn scope is required to generate unique urn
```

And since the extractor specifically requires the scope, it might be okay.

Comment (StewartJingga) [reply plugins/base_extractor.go:19]: Will that error be misleading? since it has `invalid kafka extractor config` that could point user concern to `config` block.

Comment (sudo-suhas) [reply plugins/base_extractor.go]: updated as per discussion.

**Comment by ravisuhag** [comment]
@sudo-suhas can you also add test cases for maintaining code coverage? The pipeline will break without that.

**Review by StewartJingga — APPROVED** [review]
