### PR TITLE
fix: skip config load for cmds that don't require it

### LINKED ISSUE #394: bug: config not found message on all commands that do not require it
**Describe the bug**
I keep getting below message when running all meteor commands that does not require config file
```
unable to find config file, loading from env and defaults: open ./meteor.yaml: no such file or directory
```

**To Reproduce**
1. Make sure you don't have `meteor.yaml`
2. Run `meteor list extractors`
3. See message

**Expected behavior**
Should not show `unable to find config file` message for below commands that do not require it:
1. meteor list
2. meteor info
3. meteor gen
4. others...

### PR DESCRIPTION
**Pull request by sudo-suhas**
- Load config only for 'lint' and 'run' commands. This would ensure that
  there are no warnings logs related to config file not being found for
  commands that do not require it.
- In case the config file is not present, print the error but proceed
  with defaults.
- Remove metrics/instrumentation for lint command since it does not
  provide any value.

Closes #394

### CODE REVIEW

**Comment by sudo-suhas** [comment]
```
BREAKING CHANGE: Config file not found errors were being ignored
earlier for 'meteor run' but would fail now if the config file is not
found.
```

Not 100% sure if this behaviour would be correct. More than happy to roll this back if we want to allow `meteor run` without any config file being found. However, if the config file is not found, even the default values won't be applied:

```go
package main

import (
	"fmt"

	"github.com/odpf/meteor/config"
)

func main() {
	cfg, err := config.Load("./doesnotexist.yaml")
	fmt.Printf("cfg: %#v\nerr: %s\n", cfg, err)
}
```

```

➜ go run ./.playground/cfgload.go                                                                                         
cfg: config.Config{LogLevel:"", StatsdEnabled:false, StatsdHost:"", StatsdPrefix:"", MaxRetries:0, RetryInitialIntervalSeconds:0, StopOnSinkError:false}
err: unable to find config file, loading from env and defaults: open ./doesnotexist.yaml: no such file or directory
```

**Comment by ravisuhag** [comment]
@sudo-suhas Checkout this PR as well. https://github.com/odpf/shield/pull/155 We should follow a similar approach on this. cc @mabdh @StewartJingga

File: cmd/root.go [hunk 1]
```diff
@@ -18,23 +19,23 @@ const exitError = 1
...
-		client, err := metrics.NewStatsdClient(cfg.StatsdHost)
-		if err != nil {
-			fmt.Printf("ERROR: %s\n", err.Error())
-			os.Exit(exitError)
-		}
-		mt = metrics.NewStatsdMonitor(client, cfg.StatsdPrefix)
+	mt, err := newStatsdMonitor(cfg)
+	if err != nil {
+		fmt.Printf("ERROR: %s\n", err.Error())
+		os.Exit(exitError)
```
Comment (mabdh) [inline cmd/root.go:38]: Rather than throwing `os.Exit(exitError)` here in `cmd/root`, I think it is better to handler `os.Exit` in `main.go` file. So maybe this New function could also return error and this line could just simply `return err`. wdyt? @sudo-suhas @StewartJingga

**Comment by sudo-suhas** [comment]
> @sudo-suhas Checkout this PR as well. https://github.com/odpf/shield/pull/155 We should follow a similar approach on this.

@ravisuhag could you elaborate on this a bit? Are you suggesting that we should use `github.com/odpf/salt/cmdx` for loading the config?

File: cmd/root.go (hunk 1 above)
Comment (sudo-suhas) [reply cmd/root.go]: Although this specific instance is no longer present, have done the suggested change for possible error during config load.

**Comment by ravisuhag** [comment]
> > @sudo-suhas Checkout this PR as well. [odpf/shield#155](https://github.com/odpf/shield/pull/155) We should follow a similar approach on this.
> 
> @ravisuhag could you elaborate on this a bit? Are you suggesting that we should use `github.com/odpf/salt/cmdx` for loading the config?

I think that as well, and also handling of missing config approach.

**Comment by sudo-suhas** [comment]
@ravisuhag @StewartJingga have done the changes as per our discussion and also updated the PR desc.

**Review by ravisuhag — APPROVED** [review]

**Review by mabdh — APPROVED** [review]

**Comment by sudo-suhas** [comment]
In the sync review/QA for changes, @StewartJingga recommended to still print error for `run` and `lint` commands if config file is not present. Have done this change.
